# Base Jekyll configuration

# Grunt handles some Jekyll configuration. If you set something here and
# it doesn't work, check if it is set in the Gruntfile.

# Use _config.build.yml to override these settings on `grunt build`.

name: dcalhoun.github.io
description: Personal site of David Calhoun.

author:
  name: David Calhoun
  email: hello@davidcalhoun.me
  github: dcalhoun
  twitter: david_calhoun

# Exclude directories and/or files from the conversion.
# Grunt moves image files and asset directories.
exclude: ['assets/img', 'assets/css', 'assets/js', 'assets/fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

# Force inclusion of directories and/or files in the conversion.
# .htaccess is a good example since dotfiles are excluded by default.
include: ['.htaccess']

# Default post path style
# date  /:categories/:year/:month/:day/:title.html
# pretty  /:categories/:year/:month/:day/:title/
# none  /:categories/:title.html
permalink: /:year/:month/:day/:title/

# Publish posts with future date.
# _config.build.yml sets this to false on `grunt build`
future: true

# Compile posts in the _drafts directory.
# _config.build.yml sets this to false on `grunt build`
show_drafts: true

# Split posts over multiple subdirectories called “page2”, “page3”, … “pageN”
paginate: 10
paginate_path: 'page:num'

# Markdown library
markdown: redcarpet
# Markdown library options
# redcarpet:
  # extensions: ['fenced_code_blocks', 'smart']

# Use Pygments to highlight code blocks
pygments: true
